"""Discover small public repos via the GitHub search API.

Targets: stars 200–3000, created on/before 2022-05-01, recently active, public.
Outputs a fresh `training/repos.yaml` with `train` (480) and `validation` (120).
"""

from __future__ import annotations

import os
import random
import sys
import time

import requests
import urllib3
import yaml
from dotenv import load_dotenv

load_dotenv()
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

TOKEN = os.environ["GITHUB_TOKEN"]
VERIFY = os.getenv("GITHUB_VERIFY_SSL", "true").lower() not in {"false", "0", "no"}

SESSION = requests.Session()
SESSION.headers["Authorization"] = f"Bearer {TOKEN}"
SESSION.headers["Accept"] = "application/vnd.github+json"
SESSION.verify = VERIFY


def search_page(query: str, page: int, per_page: int = 100) -> list[dict]:
    while True:
        r = SESSION.get(
            "https://api.github.com/search/repositories",
            params={"q": query, "per_page": per_page, "page": page, "sort": "stars", "order": "desc"},
            timeout=30,
        )
        if r.status_code == 403 and "rate limit" in r.text.lower():
            reset = int(r.headers.get("X-RateLimit-Reset", "0"))
            wait = max(0, reset - int(time.time())) + 5
            print(f"  rate-limit, sleeping {wait}s...", flush=True)
            time.sleep(wait)
            continue
        r.raise_for_status()
        return r.json().get("items", [])


def discover(target: int = 700) -> list[str]:
    """Return a list of `owner/repo` strings sampled from small-repo searches."""
    queries = [
        "stars:200..600 created:<2022-05-01 pushed:>2025-01-01 archived:false",
        "stars:600..1200 created:<2022-05-01 pushed:>2025-01-01 archived:false",
        "stars:1200..2500 created:<2022-05-01 pushed:>2025-01-01 archived:false",
        "stars:2500..5000 created:<2022-05-01 pushed:>2025-01-01 archived:false",
    ]
    seen: set[str] = set()
    out: list[str] = []
    for q in queries:
        for page in range(1, 11):
            items = search_page(q, page)
            if not items:
                break
            for it in items:
                full = it["full_name"]
                if full in seen:
                    continue
                if it.get("fork"):
                    continue
                if it.get("size", 0) < 50:
                    continue
                seen.add(full)
                out.append(full)
            print(f"  q={q[:50]}... page={page} -> {len(out)} total", flush=True)
            if len(out) >= target:
                return out
            time.sleep(1)  # be nice to the search API (30 req/min limit)
    return out


def main() -> None:
    print("Discovering small repos via GitHub search...", flush=True)
    repos = discover(target=700)
    print(f"Discovered {len(repos)} unique repos", flush=True)

    if len(repos) < 600:
        print(f"WARNING: only {len(repos)} repos found, need 600. Lower the target or widen queries.", flush=True)
        sys.exit(1)

    random.seed(42)
    random.shuffle(repos)
    train = sorted(repos[:480])
    validation = sorted(repos[480:600])

    overlap = set(train) & set(validation)
    assert not overlap, f"overlap: {overlap}"

    out = {"train": train, "validation": validation}
    with open("training/repos.yaml", "w", encoding="utf-8") as f:
        f.write("# Auto-discovered small public repos (stars 200-5000, created <=2022-05-01).\n")
        f.write("# Generated by training/discover_small_repos.py\n\n")
        yaml.safe_dump(out, f, default_flow_style=False, sort_keys=False)
    print(f"Wrote training/repos.yaml: {len(train)} train + {len(validation)} val", flush=True)


if __name__ == "__main__":
    main()
